package server
import "net/http"
func(s *Server)dashboard(w http.ResponseWriter,r *http.Request){w.Header().Set("Content-Type","text/html; charset=utf-8");w.Write([]byte(dashHTML))}
const dashHTML=`<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Glossary</title>
<style>:root{--bg:#1a1410;--bg2:#241e18;--bg3:#2e261e;--rust:#c45d2c;--rl:#e8753a;--leather:#a0845c;--cream:#f0e6d3;--cd:#bfb5a3;--cm:#7a7060;--gold:#d4a843;--green:#4a9e5c;--mono:'JetBrains Mono',Consolas,monospace;--serif:'Libre Baskerville',Georgia,serif}*{margin:0;padding:0;box-sizing:border-box}body{background:var(--bg);color:var(--cream);font-family:var(--mono);font-size:13px;line-height:1.6}.hdr{padding:.6rem 1.2rem;border-bottom:1px solid var(--bg3);display:flex;justify-content:space-between;align-items:center}.hdr h1{font-family:var(--serif);font-size:1rem}.hdr h1 span{color:var(--rl)}.main{max-width:700px;margin:0 auto;padding:1rem}.btn{font-family:var(--mono);font-size:.68rem;padding:.3rem .6rem;border:1px solid;cursor:pointer;background:transparent}.btn-p{border-color:var(--rust);color:var(--rl)}.btn-p:hover{background:var(--rust);color:var(--cream)}.toolbar{display:flex;gap:.5rem;margin-bottom:1rem}.toolbar input{flex:1;background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.3rem .5rem;font-family:var(--mono);font-size:.72rem;outline:none}.term{background:var(--bg2);border:1px solid var(--bg3);padding:.7rem;margin-bottom:.4rem}.term h3{font-size:.85rem;margin-bottom:.2rem}.term p{font-size:.78rem;color:var(--cd)}.term-meta{font-size:.65rem;color:var(--cm);margin-top:.2rem}.cat{font-size:.6rem;padding:0 .25rem;background:var(--bg3);color:var(--gold);border-radius:2px}.empty{text-align:center;padding:2rem;color:var(--cm);font-style:italic;font-family:var(--serif)}.modal-bg{position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,.65);display:flex;align-items:center;justify-content:center;z-index:100}.modal{background:var(--bg2);border:1px solid var(--bg3);padding:1.5rem;width:90%;max-width:500px}.modal h2{font-family:var(--serif);font-size:.9rem;margin-bottom:1rem}label.fl{display:block;font-size:.65rem;color:var(--leather);text-transform:uppercase;letter-spacing:1px;margin-bottom:.2rem;margin-top:.5rem}input[type=text],textarea{background:var(--bg);border:1px solid var(--bg3);color:var(--cream);padding:.35rem .5rem;font-family:var(--mono);font-size:.78rem;width:100%;outline:none}textarea{resize:vertical;min-height:80px}</style>
<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital@0;1&family=JetBrains+Mono:wght@400;600&display=swap" rel="stylesheet">
</head><body><div class="hdr"><h1><span>Glossary</span></h1><button class="btn btn-p" onclick="showNew()">+ Term</button></div>
<div class="main"><div id="upgrade-banner" style="display:none;background:#241e18;border:1px solid #8b3d1a;border-left:3px solid #c45d2c;padding:.6rem 1rem;font-size:.78rem;color:#bfb5a3;margin-bottom:.8rem"><strong style="color:#f0e6d3">Free tier</strong> — 10 items max. <a href="https://stockyard.dev/glossary/" target="_blank" style="color:#e8753a">Upgrade to Pro →</a></div><div class="toolbar"><input type="text" id="q" placeholder="Search terms..." onkeydown="if(event.key==='Enter')search()"><button class="btn btn-p" onclick="search()">Search</button></div><div id="list"></div></div><div id="modal"></div>
<script>
let terms=[];async function api(u,o){return(await fetch(u,o)).json()}
function esc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
async function load(){const d=await api('/api/terms');terms=d.terms||[];render()}
async function search(){const q=document.getElementById('q').value;if(!q){load();return};const d=await api('/api/search?q='+encodeURIComponent(q));terms=d.terms||[];render()}
function render(){document.getElementById('list').innerHTML=terms.length?terms.map(t=>'<div class="term"><h3>'+esc(t.name)+'</h3><p>'+esc(t.definition)+'</p><div class="term-meta">'+(t.category?'<span class="cat">'+esc(t.category)+'</span> ':'')+(t.aliases?'Aliases: '+esc(t.aliases):'')+'<span style="float:right;cursor:pointer;color:var(--cm)" onclick="del(\''+t.id+'\')">del</span></div></div>').join(''):'<div class="empty">No terms yet.</div>'}
function showNew(){document.getElementById('modal').innerHTML='<div class="modal-bg" onclick="if(event.target===this)closeModal()"><div class="modal"><h2>New Term</h2><label class="fl">Name</label><input type="text" id="n-name"><label class="fl">Definition</label><textarea id="n-def" rows="3"></textarea><label class="fl">Category</label><input type="text" id="n-cat"><label class="fl">Aliases</label><input type="text" id="n-ali" placeholder="alias1, alias2"><div style="display:flex;gap:.5rem;margin-top:1rem"><button class="btn btn-p" onclick="save()">Create</button><button class="btn" style="border-color:var(--bg3);color:var(--cm)" onclick="closeModal()">Cancel</button></div></div></div>'}
async function save(){const b={name:document.getElementById('n-name').value,definition:document.getElementById('n-def').value,category:document.getElementById('n-cat').value,aliases:document.getElementById('n-ali').value};if(!b.name){alert('Name required');return};await api('/api/terms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});closeModal();load()}
async function del(id){if(!confirm('Delete?'))return;await api('/api/terms/'+id,{method:'DELETE'});load()}
function closeModal(){document.getElementById('modal').innerHTML=''}
load()
fetch('/api/tier').then(r=>r.json()).then(j=>{if(j.tier==='free'){var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'}}).catch(()=>{var b=document.getElementById('upgrade-banner');if(b)b.style.display='block'});
</script></body></html>`
